<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PricingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricingRepository extends EntityRepository
{
    public function getRegistrationPricingFromSchoolBuilder($school_id) {

        $qb = $this->_em->createQueryBuilder()
            ->select('p')
            ->from($this->_entityName, 'p')
            ->leftJoin('p.school', 's')
            ->leftJoin('p.pricingCategory', 'c')
            ->where('s.id = :school_id')
            ->andWhere('c = p.pricingCategory')
            ->andWhere('c.name = :category')
            ->setParameter('school_id', $school_id)
            ->setParameter('category', 'Tarif Inscription');

        return $qb;
    }
}
