<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SchoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolRepository extends EntityRepository
{

    public function getSchoolsQuery()
    {
        $qb = $this->_em->createQueryBuilder()
           ->select('s')
           ->from($this->_entityName, 's')
           ->orderBy('s.name');

        return $qb->getQuery();
    }
    public function findSchoolFromManager(array $params)
    {
        $qb = $this->_em->createQueryBuilder()
           ->select('s')
           ->from($this->_entityName, 's')
           ->where('s.user = :userId')
           ->andWhere('s.id = :id')
           ->setParameter('userId', $params['userId'])
           ->setParameter('id', $params['id']);

        return $qb->getQuery()
                  ->getOneOrNullResult();
    }
}
